# script by shermond l. lostan
import time
print("==========[]==========[]=[termux+theme]=[]==========[]=========")
print("()-----------------------------------------------------------()")
print("()--developer-:-shermond-l.lostan----------------------------()")
print("()-----------------------------------------------------------()")
print("()--organzazion-:-CGHHA--------------------------------------()")
print("()-----------------------------------------------------------()")
print("()--version-:-1.0--------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("()-----------------------------------------------------------()")
print("===============================================================")
print("")
print("selamat datang di termux theme!! silahkan pilih no di bawah")
print("")
print("1.script termux theme bisa ganti nama + cowsay eyes")
print("")
print("2.script termux theme figlet")
print("")
print("3.keluar")
print("")
pilih = input("pilih no : ")

if pilih == "1":
 print("")
 print("copy teks berikut :")
 print("")
 print("# welcome this is termux screen by awerty hacker")
 print("# command not found handle")
 print("if [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ]; then")
 print("command_not_found_handle() {")
 print("/data/data/com.termux/files/usr/libexec/termux/command-not-found")
 print("}")
 print("fi")
 print("clear")
 print("cowsay -f eyes *teks kamu*")
 print("neofetch")
 print("fish")
 print("PS1='nama kamu > '")

elif pilih == "2":
 print("")
 print("copy teks berikut :")
 print("")
 print("# welcome this is termux screen by awerty hacker")
 print("# command not found handle")
 print("if [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found>")
 print("command_not_found_handle() {")
 print("/data/data/com.termux/files/usr/libexec/termux/command-not-found")
 print("}")
 print("fi")
 print("clear")
 print("figlet teks kamu ")
 print("fish")
 print("PS1='nama hakcer kamu > '")

if pilih == "3":
 print("")
 print("shortcut keluar CTRL + Z")
else:
 print("input yang anda masukkan salah!!")
